# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Nopeus < Formula
  desc "Nopeus by Salfati Group is an end-to-end tool to manage your cloud applications in a single command"
  homepage "https://nopeus.co"
  version "0.1.0"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f0ec1dc35fa3decaf637dc624e084d8fccfa50e494f715faa72473fa6820bcde"

      def install
        bin.install "nopeus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ea4b1356939bbb9fe38f603770cc24e50fb2473b0292a2fa28b9e31093cb44be"

      def install
        bin.install "nopeus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Linux_armv7.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "94eeab856693f84e3fc072965838e6b71ca49c16e5cd60ba2bebadb229f5de8e"

      def install
        bin.install "nopeus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8e5acc7cf91555955ddbc08303e1e2ea16e5e1fce8695486cd47f10c887a7196"

      def install
        bin.install "nopeus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "92ab76e8c75388656d0ff54f6a04d70da947f98738a1a5dc1d987b9c55afdd4a"

      def install
        bin.install "nopeus"
      end
    end
  end

  test do
    system "#{bin}/nopeus --version"
  end
end
