# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nopeus < Formula
  desc "Nopeus by Salfati Group is an end-to-end tool to manage your cloud applications in a single command"
  homepage "https://nopeus.co"
  version "0.1.0"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Darwin_arm64.tar.gz"
      sha256 "3b92071b1e6bcb49597a8395ca6ead02734613b047dfffadeea78c9b8bd9b961"

      def install
        bin.install "goreleaser"
        bash_completion.install "completions/nopeus.bash" => "nopeus"
        zsh_completion.install "completions/nopeus.zsh" => "_nopeus"
        fish_completion.install "completions/nopeus.fish"
        man1.install "manpages/nopeus.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Darwin_x86_64.tar.gz"
      sha256 "7409adb084c774354a57101044a287636ccc775920807f6ebee8ccea013899b7"

      def install
        bin.install "goreleaser"
        bash_completion.install "completions/nopeus.bash" => "nopeus"
        zsh_completion.install "completions/nopeus.zsh" => "_nopeus"
        fish_completion.install "completions/nopeus.fish"
        man1.install "manpages/nopeus.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Linux_armv7.tar.gz"
      sha256 "849165dbf31c7a3a5b6aed353b536e21597792772fa45148b7d0ee30506a2326"

      def install
        bin.install "goreleaser"
        bash_completion.install "completions/nopeus.bash" => "nopeus"
        zsh_completion.install "completions/nopeus.zsh" => "_nopeus"
        fish_completion.install "completions/nopeus.fish"
        man1.install "manpages/nopeus.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Linux_arm64.tar.gz"
      sha256 "e2adfea6b7d84938527bfbe6a4b292265e881b50f9760659bb53d15a74bc72b3"

      def install
        bin.install "goreleaser"
        bash_completion.install "completions/nopeus.bash" => "nopeus"
        zsh_completion.install "completions/nopeus.zsh" => "_nopeus"
        fish_completion.install "completions/nopeus.fish"
        man1.install "manpages/nopeus.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/salfatigroup/nopeus/releases/download/v0.1.0/nopeus_Linux_x86_64.tar.gz"
      sha256 "2f9667dd80f4f49524d24efc6afb80e1fd266ced1db9f43dfcaf1beb254f4eae"

      def install
        bin.install "goreleaser"
        bash_completion.install "completions/nopeus.bash" => "nopeus"
        zsh_completion.install "completions/nopeus.zsh" => "_nopeus"
        fish_completion.install "completions/nopeus.fish"
        man1.install "manpages/nopeus.1.gz"
      end
    end
  end

  test do
    system "#{bin}/nopeus --version"
  end
end
